import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import { ViewGridIcon,MicrophoneIcon } from '@heroicons/react/solid'
import {SearchIcon} from "@heroicons/react/outline"
import Footer from '../components/Footer'
import { useRef } from 'react'
import { useRouter } from 'next/router'
export default function Home() {
  const router = useRouter();
  const searchInputRef=useRef(null);

  const search=(e)=>{
    e.preventDefault();
    const term = searchInputRef.current.value;
    if(!term) return;
    router.push(`./search?term=${term}`);

  }
  return (
    <div className='flex flex-col items-center h-screen'>
      <Head>
        <title>CodingOp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='flex w-full p-5 justify-between text-sm text-gray-700'>
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
        </div>
        <div className='flex space-x-4 items-center'>
          <p className='link'> <a href="https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox">Email</a></p>
          <p className='link'>Images</p>
          <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer'/>
          <Avatar url="https://avatars.githubusercontent.com/u/84802635?v=4"/>
        </div>
      </header>
      <form className='flex flex-col items-center mt-32 flex-grow w-4/5'>
        <Image
        src="/logo.png"
        height={150}
        width={600}
        />
        <div className='flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl'>
          <SearchIcon className='h-5 mr-3 text-gray-500'/>
          <input ref={searchInputRef} type="text" className='flex-grow focus:outline-none'></input>
          <MicrophoneIcon className='h-5'/>
        </div>
        <div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4'>
          <button onClick={search} className='btn'>Op Search</button>
          <button onClick={search} className='btn'>Want Some Coffee?</button>
        </div>
      </form>
      <Footer/>
    </div>
  )
}
